### ISSUE TITLE
panic: Failed to process committed block

### ISSUE THREAD

**Issue by GooSatoru** [okx/exchain#1017]
## operation steps

1、download snapshots

```
 wget https://ok-public-hk.oss-cn-hongkong.aliyuncs.com/cdn/okexchain/snapshot/mainnet-s1-20210905-5351432.tar.gz
```

2、compile binaries from source

```
git clone -b v0.19.1 https://github.com/okex/exchain.git
cd exchain
make mainnet
```

3、start node

```
export EXCHAIND_PATH=/data/exchaind/
export EXCHAIN_SEEDS="e926c8154a2af4390de02303f0977802f15eafe2@3.16.103.80:26656,7fa5b1d1f1e48659fa750b6aec702418a0e75f13@35.177.8.240:26656,c8f32b793871b56a11d94336d9ce6472f893524b@18.167.16.85:26656"
exchaind start --home /data/.exchaind/ --chain-id exchain-66  --mempool.sort_tx_by_gp --home ${EXCHAIND_PATH} --p2p.seeds "e926c8154a2af4390de02303f0977802f15eafe2@3.16.103.80:26656,7fa5b1d1f1e48659fa750b6aec702418a0e75f13@35.177.8.240:26656,c8f32b793871b56a11d94336d9ce6472f893524b@18.167.16.85:26656"
```

## node panic while after a while

```
panic: Failed to process committed block (5355801:EDB99CC2643279770CD3A06CDA5169BE5F3A8943D5644A5A6A147A29AB598372): wrong Block.Header.AppHash.  Expected 3F21CC5D5F6B91AED7D7FFD87D809218AF8B996029896BEF033419C779603214, got F674BA0BDB959E9288AB52F574AB4037FF5CB28FAF28FA442640D867A4E232ED

goroutine 245 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc002a5a4e0)
        /root/gopath/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain9/blockchain/v0/reactor.go:349 +0x17be
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/gopath/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain9/blockchain/v0/reactor.go:118 +0xdb
```

**Comment by xiangjianmeng** [comment]
We did not reproduce this error after strictly following your steps.

**Comment by GooSatoru** [comment]
> We did not reproduce this error after strictly following your steps.

two machines on my side have crashed and reproduced twice.

Both ubuntu 20.04.2 TLS

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by xiangjianmeng** [comment]
> > We did not reproduce this error after strictly following your steps.
> 
> two machines on my side have crashed and reproduced twice.
> 
> Both ubuntu 20.04.2 TLS
> 
> ```
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.2 LTS
> Release:	20.04
> Codename:	focal
> ```

What are the architecture of your two machines? Please use `uname -a` to show the architecture.

**Comment by GooSatoru** [comment]
> `uname -a`
```
Linux ubuntu 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
also show error bellow
```
I[2021-09-15|03:00:17.335][1414601] starting ABCI with Tendermint                module=main
I[2021-09-15|03:00:19.613][1414601] Interval<2811ms>, ApplyBlock<5355801>, tx<6>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 3F21CC5D5F6B91AED7D7FFD87D809218AF8B996029896BEF033419C779603214, got F674BA0BDB959E9288AB52F574AB4037FF5CB28FAF28FA442640D867A4E232ED
```

**Comment by LtSnakePlissken** [comment]
Hi, I'm getting this error as well. Twice now and unable to resume. Would you kindly have any tips regarding restarting it without losing progress?

**Comment by xiangjianmeng** [comment]
> Hi, I'm getting this error as well. Twice now and unable to resume. Would you kindly have any tips regarding restarting it without losing progress?

which commit did you use? and which height did the error occur?

**Comment by lisuxiaoqi** [comment]
Could you please take a shot at the v1.6.5.1 release and the latest snapshot?  Let us know if it can help
