### ISSUE TITLE
failed to load mint Store: wanted to load target 23757234 but only found up to 23757200

### ISSUE THREAD

**Issue by ghost** [okx/exchain#3263]
## 1. 详细描述
启动节点报错

## 2. 硬件配置

物理机器，ubuntu20:04 

## 3. exchaind版本号
v1.7.0

## 4. 日志
failed to load feesplit Store: wanted to load target 23757234 but only found up to 23757200

## 5. 网络
- [x] 主网
- [ ] 测试网

**Comment by ghost** [comment]
使用
`exchaind repair-state --home ${EXCHAIND_PATH}` 后 继续报错：

`2023/11/23 03:29:45 repair state latestBlockHeight = 23757234    commitVersion = 23757200
2023/11/23 03:29:45 repair state at version = 23757198
panic: failed to load token Store: wanted to load target 23757198 but only found up to 23757100

goroutine 1 [running]:
github.com/okex/exchain/app.panicError(...)
        /tmp/exchain/app/repair_state.go:346
github.com/okex/exchain/app.RepairState(0xc00051edc8, 0x0)
        /tmp/exchain/app/repair_state.go:144 +0x7d8
main.repairStateCmd.func2(0xc000300500, {0xc000532b00, 0x0, 0x2})
        /tmp/exchain/cmd/exchaind/repair_data.go:40 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000300500, {0xc000532ae0, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f4f00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/okex/exchain/libs/tendermint/libs/cli.Executor.Execute({0xc0001f4f00, 0x25c2bd0})
        /tmp/exchain/libs/tendermint/libs/cli/setup.go:89 +0x36
main.main()
        /tmp/exchain/cmd/exchaind/main.go:121 +0x7ba`

**Comment by chengzhinei** [comment]
> 使用 `exchaind repair-state --home ${EXCHAIND_PATH}` 后 继续报错：
> 
> `2023/11/23 03:29:45 repair state latestBlockHeight = 23757234 commitVersion = 23757200 2023/11/23 03:29:45 repair state at version = 23757198 panic: failed to load token Store: wanted to load target 23757198 but only found up to 23757100
> 
> goroutine 1 [running]: github.com/okex/exchain/app.panicError(...) /tmp/exchain/app/repair_state.go:346 github.com/okex/exchain/app.RepairState(0xc00051edc8, 0x0) /tmp/exchain/app/repair_state.go:144 +0x7d8 main.repairStateCmd.func2(0xc000300500, {0xc000532b00, 0x0, 0x2}) /tmp/exchain/cmd/exchaind/repair_data.go:40 +0x6b github.com/spf13/cobra.(*Command).execute(0xc000300500, {0xc000532ae0, 0x2, 0x2}) /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f4f00) /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) /root/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918 github.com/okex/exchain/libs/tendermint/libs/cli.Executor.Execute({0xc0001f4f00, 0x25c2bd0}) /tmp/exchain/libs/tendermint/libs/cli/setup.go:89 +0x36 main.main() /tmp/exchain/cmd/exchaind/main.go:121 +0x7ba`

带上--start-height=23757100 重新再执行一下试试。如果继续出现类似错误，更新这个高度为only found up to 后面那个值
