### ISSUE TITLE
Mainnet. Peer crashed on block synchronization from genesis block

### ISSUE THREAD

**Issue by artjoma** [okx/exchain#771]
## Summary of Bug
```
I[2021-03-24|14:36:45.884][43059] Summary: Height<143820>, Interval<0s>, Abci<32ms>, Tx<1>,   module=main 
I[2021-03-24|14:36:45.884][43059] Committed state                              module=state height=143820 txs=1 appHash=FE7FEECF139E55FBC949DD33C7417228514A918B458BF64C1FF39DE7558E6BB9
I[2021-03-24|14:36:45.918][43059] Executed block                               module=state height=143821 validTxs=0 invalidTxs=1
I[2021-03-24|14:36:45.925][43059] Module: Height<143821>, module<token>, BeginBlock<0ms>, DeliverTx<0ms>, TxNum<1>, EndBlock<0ms>, module=main 
I[2021-03-24|14:36:45.925][43059] Handler: Height<143821>, module<token>, DeliverTx<handleMsgSend>, elapsed<0ms>, invoked<1>, module=main 
I[2021-03-24|14:36:45.925][43059] App: Height<143821>, BeginBlock<4ms>, DeliverTx<1ms>, txElapseBySum<0ms>, EndBlock<0ms>, Commit<5ms>, Tx<1>, token[handler<0ms>, (begin+end)block<0ms>, tx<1>] module=main 
I[2021-03-24|14:36:45.925][43059] Summary: Height<143821>, Interval<0s>, Abci<11ms>, Tx<1>,   module=main 
I[2021-03-24|14:36:45.925][43059] Committed state                              module=state height=143821 txs=1 appHash=AE0DB0427DDB73C99A9C278AE4DD4ED0C136D09E522613CB2F592348470089A1
panic: Failed to process committed block (143822:EBF2437400B76BCAFF70B483E54BD06082F1DD6C7CF9B28EB3AE9260311758F6): wrong Block.Header.LastResultsHash.  Expected 327FC93C53DCC6FE3BCAFA5F92CD40B486C379758A359FF3A322F1B1DED0486B, got 488D63B7C793A727B8E0DE2B4BAC69071FF82D46DB73D88DEB55CE13E574B1B0

goroutine 164 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0005c76c0)
        /home/art/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain5.0.20210322061756-1d7f05428780/blockchain/v0/reactor.go:349 +0x13df
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /home/art/go/pkg/mod/github.com/okex/tendermint@v0.33.9-okexchain5.0.20210322061756-1d7f05428780/blockchain/v0/reactor.go:118 +0x87

```
### 1. Describe
No way to setup Mainnet peer. Every time process crashed on block number 143821

### 2. Impact
OS process terminated

### 3. Recover
On startup OS process crashed on block 143821

## Expected Result
Peer should download all blocks from 0 till current Mainnet head block

## Version
master

## Steps to Reproduce
Documentation: https://okexchain-docs.readthedocs.io/en/latest/getting-start/join-okexchain-mainnet.html 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by zhongqiuwood** [comment]
Please follow this document:
https://github.com/okex/mainnet/blob/main/README.md

Make sure https://github.com/okex/okexchain/releases/tag/v0.16.3 is used

**Comment by artjoma** [comment]
Thank you! Branch v0.16.3 works fine.
