### ISSUE TITLE
调用eth_getBlockByNumber获取创世区块信息，但是返回的结果看起来像是当前的最新区块，这与以太坊的逻辑不一致

### ISSUE THREAD

**Issue by ryuuyq** [okx/exchain#788]
### 1. Describe
调用eth_getBlockByNumber获取创世区块信息，但是返回的结果看起来像是当前的最新区块，这与以太坊的逻辑不一致。

`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", false],"id":1}' -H "Content-Type: application/json" https://exchaintest.okexcn.com`

因此，在使用graph-node的时候，除了第一次启动能正常外，后续的启动都会报错：`thread 'tokio-runtime-worker' panicked at 'Creating the BlockStore works: Unknown(the genesis block hash for chain mainnet has changed from xxxx  to xxxx since the last time we ran)', node/src/store_builder.rs:230:14`

```
graph-node_1  | Mar 31 02:28:50.322 INFO Connected to Ethereum, capabilities: archive, trace, network_version: 65, network: mainnet
graph-node_1  | thread 'tokio-runtime-worker' panicked at 'Creating the BlockStore works: Unknown(the genesis block hash for chain mainnet has changed from 38916edcc6ac65a288e1e9995903fff9720bde18effd5e068a9e9aa523aaef18 to e715c4cc22b2899ea303aa27059fa260159b972d58730e7917a6e27fc83feb03 since the last time we ran)', node/src/store_builder.rs:230:14
graph-node_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
graph-node_1  | Panic in tokio task, aborting!
graph-node_1  | /usr/local/bin/start: line 52:    33 Aborted                 (core dumped) graph-node --node-id "${node_id//-/_}" --postgres-url "$postgres_url" --ethereum-rpc $ethereum --ipfs "$ipfs"
docker-graph-node_graph-node_1 exited with code 134

```

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpiersZ** [comment]
我也遇到了同样的问题，使用 https://exchainrpc.okex.org
```
Aug 12 04:14:31.300 INFO Graph Node version: 0.18.0 :: hosted-current (0e3dfb22c 2020-06-23)
Aug 12 04:14:31.311 INFO Starting up
Aug 12 04:14:31.311 INFO Trying IPFS node at: http://127.0.0.1:5001/
Aug 12 04:14:31.316 INFO Creating transport, url: https://exchainrpc.okex.org, network: okchain
Aug 12 04:14:31.316 INFO Successfully connected to IPFS node at: http://127.0.0.1:5001/
Aug 12 04:14:31.321 INFO Connecting to Postgres, conn_pool_size: 10, url: postgresql://postgres:HIDDEN_PASSWORD@localhost:5432/graph-node
Aug 12 04:14:31.329 INFO Connected to Postgres, url: postgresql://postgres:HIDDEN_PASSWORD@localhost:5432/graph-node, component: Store
Aug 12 04:14:31.332 INFO Connecting to Ethereum..., network: okchain
Aug 12 04:14:31.455 INFO Connected to Ethereum, network_version: 66, network: okchain
Aug 12 04:14:31.456 INFO Waiting for other graph-node instances to finish migrating, component: Store
Aug 12 04:14:31.456 INFO Running migrations, component: Store
Aug 12 04:14:31.457 INFO Migrations finished, component: Store
Aug 12 04:14:31.457 INFO Completed pending Postgres schema migrations, component: Store
thread 'tokio-runtime-worker' panicked at 'Ethereum node provided genesis block hash 0xb793…c494, but we expected dbbc1cbe4cee3deac2c71b037984fdcf08369c6b517fc421b857761a4fed896f. Did you change networks without changing the network name?', store/postgres/src/store.rs:271:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: graph_store_postgres::store::Store::new
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  15: <futures::stream::map::Map<S,F> as futures::stream::Stream>::poll
  16: <futures::stream::collect::Collect<S> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: futures::future::chain::Chain<A,B,C>::poll
  19: futures::task_impl::std::set
  20: <futures_util::future::try_future::unwrap_or_else::UnwrapOrElse<Fut,F> as core::future::future::Future>::poll
  21: tokio::runtime::task::core::Core<T,S>::poll
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::worker::Context::run_task
  26: tokio::runtime::thread_pool::worker::Context::run
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
  28: tokio::runtime::thread_pool::worker::run
  29: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  31: tokio::runtime::task::harness::Harness<T,S>::poll
  32: tokio::runtime::blocking::pool::Inner::run
  33: tokio::runtime::context::enter
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Panic in tokio task, aborting!
Aborted (core dumped)
```

**Comment by banishee** [comment]
https://forum.okt.club/d/180-oecthegraph
There is a simple way of building graph-node, have a try
