### ISSUE TITLE
节点正常运行一段时间后崩溃退出

### ISSUE THREAD

**Issue by nining** [okx/exchain#981]
## 1. 详细描述
节点正常运行一段时间后崩溃退出，而且一定会崩溃，运行时间大约几分钟到几十分钟都有可能

## 2. 硬件配置
Ubuntu 20.04.2 x86_64 Linux 5.11.0-27-generic

## 3. exchaind版本号
0.18.18

## 4. 日志
```
goroutine 328 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc005b2a960, 0xc0013784e0, 0x28, 0xc00be0a8c0, 0x4adf71)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain6/blockchain/v2/processor.go:91 +0x145
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc005b2a960, 0x25fc780, 0xc00f2f7e00, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain6/blockchain/v2/processor.go:131 +0x18b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc001ae7c80)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain6/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain6/blockchain/v2/reactor.go:231 +0xf2
panic: duplicate block enqueued by processor

goroutine 325 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc00163fb30, 0xc0081b9590, 0x28, 0xc003163340, 0x4b0625)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:91 +0x145
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc00163fb30, 0x26027c0, 0xc00a692810, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:131 +0x18b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc000630b40)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:231 +0xf2
panic: duplicate block enqueued by processor

goroutine 403 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc0087a9410, 0xc000561b30, 0x28, 0xc00896e000, 0x4b779c)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:91 +0x145
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc0087a9410, 0x26027c0, 0xc017c5c4c8, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:131 +0x18b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc0087ee2a0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:231 +0xf2
panic: duplicate block enqueued by processor

goroutine 409 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc009134540, 0xc0052f6060, 0x28, 0xc012962000, 0x4ba628)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:91 +0x145
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc009134540, 0x26027c0, 0xc007ec97e8, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:131 +0x18b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc006590660)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:231 +0xf2
panic: processed height 4958542 but expected height 4958541

goroutine 257 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handleBlockProcessed(0xc00589f570, 0x4ba94e, 0xc008c55d10, 0x28, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/scheduler.go:556 +0x350
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handle(0xc00589f570, 0x2602700, 0xc0130ca900, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/scheduler.go:699 +0x14a
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc00786a660)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:230 +0xc5
panic: duplicate block enqueued by processor

goroutine 268 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(0xc006f363f0, 0xc0021ce030, 0x28, 0xc0111f0000, 0x4bad8b)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:91 +0x145
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc006f363f0, 0x26027c0, 0xc0138efa28, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/processor.go:131 +0x18b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc000649620)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:231 +0xf2
panic: processed height 4969124 but expected height 4969123

goroutine 434 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handleBlockProcessed(0xc0092c3260, 0x4bd2a4, 0xc00e3e1470, 0x28, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/scheduler.go:556 +0x350
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handle(0xc0092c3260, 0x2602700, 0xc0112c1f50, 0x0, 0x0, 0x0, 0x0)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/scheduler.go:699 +0x14a
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc0096e1c80)
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/routine.go:79 +0x4d1
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).Start
	/home/okt/go/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v2/reactor.go:230 +0xc5
```
## 5. 网络
- [x] 主网
- [ ] 测试网

**Comment by zhongqiuwood** [comment]
fixed by https://github.com/okex/tendermint/pull/54
