### ISSUE TITLE
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 051A59044F8DF01A9DF9CAC8D2B86DE475997B6B9A7EE5C6F3D014CD9CA8A96E, got 46B66AE2F88811C929D5B85418504035ED32BF3181E621D6A6242A96C706060C

### ISSUE THREAD

**Issue by masayil** [okx/exchain#984]
## 1. 详细描述
2021年8月80日19：30 有6台机器，在同一时间都不同步，重启服务后出现日志中报错。尝试过把0.18.14更新至0.18.17，任然无法解决

## 2. 硬件配置

物理机
ubuntu20.04
24C 128G 使用ceph存储
## 3. exchaind版本号
0.18.14

## 4. 日志
使用supervisor管理
err日志：
        /root/gowork/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v0/reactor.go:349 +0x1be9
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/gowork/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v0/reactor.go:118 +0xb0
panic: Failed to process committed block (5217260:3BD4CA22EA7D670A6CE68721E3A597E53D0CD9DF4940F78303852B311C1F3AED): wrong Block.Header.LastResultsHash.  Expected 051A59044F8DF01A9DF9CAC8D2B86DE475997B6B9A7EE5C6F3D014CD9CA8A96E, got 46B66AE2F88811C929D5B85418504035ED32BF3181E621D6A6242A96C706060C

goroutine 188 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc036b1a1a0)
        /root/gowork/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v0/reactor.go:349 +0x1be9
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /root/gowork/pkg/mod/github.com/okex/tendermint@v0.33.9-exchain8/blockchain/v0/reactor.go:118 +0xb0

out日志：
I[2021-08-21|07:33:36.495][3382221] starting ABCI with Tendermint                module=main
I[2021-08-21|07:34:00.684][3382221] Interval<24357ms>, ApplyBlock<5217260>, tx<12>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 051A59044F8DF01A9DF9CAC8D2B86DE475997B6B9A7EE5C6F3D014CD9CA8A96E, got 46B66AE2F88811C929D5B85418504035ED32BF3181E621D6A6242A96C706060C
I[2021-08-21|07:34:02.120][3382259] starting ABCI with Tendermint                module=main
I[2021-08-21|07:34:26.296][3382259] Interval<24349ms>, ApplyBlock<5217260>, tx<12>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 051A59044F8DF01A9DF9CAC8D2B86DE475997B6B9A7EE5C6F3D014CD9CA8A96E, got 46B66AE2F88811C929D5B85418504035ED32BF3181E621D6A6242A96C706060C
I[2021-08-21|07:34:27.716][3382293] starting ABCI with Tendermint                module=main
I[2021-08-21|07:34:51.960][3382293] Interval<24411ms>, ApplyBlock<5217260>, tx<12>, elapsed<0ms>, validateBlock<0ms> module=main
error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 051A59044F8DF01A9DF9CAC8D2B86DE475997B6B9A7EE5C6F3D014CD9CA8A96E, got 46B66AE2F88811C929D5B85418504035ED32BF3181E621D6A6242A96C706060C
I[2021-08-21|07:34:52.752][3382438] starting ABCI with Tendermint                module=main

## 5. 网络
- [ ] 主网
- [x] 测试网

**Comment by masayil** [comment]
supervisor配置文件：
[program:okex-test]
command=exchaind start  --chain-id okexchain-65 --home /root/okex-test/node --wsport 18546 --rpc.laddr "tcp://0.0.0.0:16657" --p2p.laddr "tcp://0.0.0.0:16656" --rest.laddr "tcp://0.0.0.0:36659" --prof_laddr "0.0.0.0:16060" --max-open 65536 --rpc.rate-limit-count 50000 --rpc.rate-limit-burst 60000
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/okex-test.err.log
stdout_logfile=/var/log/supervisor/okex-test.out.log
